- hosts: localhost
  become: true
  vars:
    my_username: wrock
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    #- include: tasks/cron.yml #Periodically ansible-pull, -o flag only pulls when there is a repo change
    - include: tasks/gnome.yml
    - include: tasks/bashrc.yml
